### ISSUE TITLE
The Exclude Folders from stats option is not working

### ISSUE THREAD

**Issue by kaffarell** [arzzen/git-quick-stats#102]
**Describe the bug**
I execute `export _GIT_PATHSPEC=':!docs'` in the terminal and there are no errors, however when I execute git-quick-stats and press for example 1 it shows:
`fatal: unrecognized argument: -- :!docs
	total:`

**To Reproduce**
1. `export _GIT_PATHSPEC=':!docs'` in the terminal
2. Open ./git-quick-stats and press 1

**Expected behavior**
It should show the stats without the specified folder

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04, Shell: zsh

**Comment by tomice** [comment]
Thanks for reporting the bug! Made a change that I believe fixes the issue. Let me know if this works out for you on your end and fixes the issue you are seeing.

**Comment by kaffarell** [comment]
Works for me :tada: , thank you!
