### ISSUE TITLE
White-spaces are not excluded

### ISSUE THREAD

**Issue by SamAriafar** [arzzen/git-quick-stats#104]
In my opinion you'd rather exclude white-spaces (indention, new lines, etc.) from insertion stats, since many editors automatically arrange those sort of things while no job is really done by the developer.

**Comment by arzzen** [comment]
Hi @SamAriafar 
a new feature was implemented if you want to ignore spaces, 
you can use the following: `export _GIT_LOG_OPTIONS="--ignore-all-space --ignore-cr-at-eol"`
