### ISSUE TITLE
Get results on a specific date range

### ISSUE THREAD

**Issue by SamAriafar** [arzzen/git-quick-stats#105]
Currently we only can see the results related to last 10 days. It would be great if we can set a to/from date range to gather the exact result we need.

**Comment by tomice** [comment]
For git-quick-stats, we have the $_GIT_SINCE and $_GIT_UNTIL variables to help narrow down the range you'd like to query. Are these not working for your use case? If they're not, could you provide a more detailed example of what you're looking for and trying to do?

**Comment by SamAriafar** [comment]
> 
> 
> For git-quick-stats, we have the $_GIT_SINCE and $_GIT_UNTIL variables to help narrow down the range you'd like to query. Are these not working for your use case? If they're not, could you provide a more detailed example of what you're looking for and trying to do?
