### ISSUE TITLE
posix shell adoption (enhancment idea)

### ISSUE THREAD

**Issue by mcpcpc** [arzzen/git-quick-stats#107]
**Is your feature request related to a problem? Please describe.**

while bash is widely accepted, it is not as versatile or cross-platform compatible as POSIX shell. 

**Describe the solution you'd like**

Suggesting a “gradual” conversion to POSIX Shell.

i am willing to help with the conversion process if it seems reasonable to you.  

**Describe alternatives you've considered**

Keep “as is” or fork it as another related project. 

**Additional context**

i use KISS Linux, which uses ash (no bash support by default).

**Comment by arzzen** [comment]
@mcpcpc thanks, I appreciate it, I'll be happy if you work it out

**Comment by mcpcpc** [comment]
closing for now.  will start a new issue to track the conversation progress.
