### ISSUE TITLE
Create a basher package

### ISSUE THREAD

**Issue by marceloboeira** [arzzen/git-quick-stats#11]
It would be awesome to install over basher 😉 

See: https://github.com/basherpm/basher

**Comment by kajyr** [comment]
Also an homebrew install would be nice to have

**Comment by arzzen** [comment]
@kajyr in progress: https://github.com/Homebrew/homebrew-core/pull/10011

**Comment by marceloboeira** [comment]
@arzzen great!

**Comment by arzzen** [comment]
@kajyr @marceloboeira merged into [homebrew](https://github.com/Homebrew/homebrew-core/pull/10011)
