### ISSUE TITLE
Don't print escape sequences to non-ttys

### ISSUE THREAD

**Issue by djpohly** [arzzen/git-quick-stats#122]
**Describe the bug**
When the output of git-quick-stats is redirected or piped, there are still terminal escape sequences for colors in the output.

**To Reproduce**
1. Run the program with output redirected to a file:

        git quick-stats -T > file.txt

2. Open the file in an editor.
3. Note the escape sequences such as `\e[31m` in the file.

**Expected behavior**
Terminal escape sequences are only printed to terminals.

**Desktop (please complete the following information):**
 - OS: Linux (Arch)
 - Version: git 4d2621b

**Suggested fix**
The quickest fix is probably to set color variables only if `test -t 1` succeeds.

**Comment by tomice** [comment]
Another option is to remove all colors from `optionPicked()`. This would prevent those colors from showing up because I think it's just in the message at the beginning. What are your thoughts, @arzzen ?

**Comment by arzzen** [comment]
@tomice, I'm ok with that
