### ISSUE TITLE
Word "commit" in commit-message increases commit count in daily status

### ISSUE THREAD

**Issue by pawaer** [arzzen/git-quick-stats#126]
**Describe the bug**
Using the option:x
    5) My daily status:
The count of commits is additionally increased by lines mentioning "commit" in the commit message.

**To Reproduce**
Commiting one commit with the commit message:
" [...] **commit** 

Further [...] **commit**"

**Expected behavior**
The daily commit count shall be 1 but is 3 (1 for the actual commit and 2 for the commit-word in the commit-message.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur

**Comment by arzzen** [comment]
@pawaer  Thanks for your first contribution to git-quick-stats! 
Without people like you submitting PRs we couldn't run this project. You rock!
