### ISSUE TITLE
How can I exclude multiple files from the statistics?

### ISSUE THREAD

**Issue by maaft** [arzzen/git-quick-stats#132]
Is this currently possible?

How would I need to set _GIT_PATHSPEC such that all `*generated.go`, `*generated.tsx` files and all files in `foo/bar/*` will be excluded?

**Comment by tomice** [comment]
Have you tried `export _GIT_PATHSPEC="*generated.go *generated.tsx foo/bar/*"`

**Comment by maaft** [comment]
yes, but how can I be sure that the files are really excluded? Is there an option to get a list of all considered files?

**Comment by tomice** [comment]
I think the easiest way to do that would be to compare between the code I gave above, then unsetting it, and see if the results are indeed excluding what you are expecting. Is there a bug or problem with chaining multiple files when utilizing the `_GIT_PATHSPEC` variable that you are experiencing?

**Comment by maaft** [comment]
No, not really. It' just a huuuuge project with tons of generated files that's all. I think I'll try on a smaller example-project to gain some confidence - thanks!
