### ISSUE TITLE
Aggregate results based on email instead of name

### ISSUE THREAD

**Issue by michalxo** [arzzen/git-quick-stats#140]
It would be cool, if you could aggregate results based on emails instead of names.

Currently those are 2 different users, but in real life it's 1 user with wrongly set up name(s).
```
Alice A <aliceaalice@work.com>
Alice Alice <alicealice@work.com>
```

**Comment by arzzen** [comment]
Hi @michalxo , it is possible to respect these different users (= alias to same person) via .mailmap file 
- see #33 
- more info https://git-scm.com/docs/gitmailmap
