### ISSUE TITLE
cygwin make install

### ISSUE THREAD

**Issue by Joopmicroop** [arzzen/git-quick-stats#15]
when I run 'make install' in cygwin I get:
`install -m 0755 git-quick-stats /usr/local/bin
      0 [main] make 10516 child_info_fork::abort: C:\cygwin32\bin\cygcrypt-0.dll: Loaded to different address: parent(0xE0000) != child(0x67700000)
make: fork: Resource temporarily unavailable`

When I ran the commands in the install section of the makefile, seperately in shell all worked without errors.
I've tried 'make install' in a cygwin with administrator rights and without, both gave me the same error.

I haven't had this problem at home when I tried this with cygwin... So maybe something cygwin related?? Don't know..

**Comment by arzzen** [comment]
you can try cygwin:
* [installer](https://gist.github.com/arzzen/35e09866dfdadf2108b2420045739245) 
* [uninstaller](https://gist.github.com/arzzen/21c660014d0663b6c5710014714779d6)
