### ISSUE TITLE
Single stats for the same author with multiple username and/or email

### ISSUE THREAD

**Issue by javaDeveloperKid** [arzzen/git-quick-stats#156]
**Is your feature request related to a problem? Please describe.**
I often work with repositories where single user creates commits with different username and/or email. This can happen for different reasons: git is configured differently on a computer in a workplace and on a computer at home; commits are from Web UI where a user has different name/email; user changed an email after some time;

**Describe the solution you'd like**
I would like to somehow tell git-quick-stats to consider given author keywords as the same author.
Example:
John Kravecki john.kravecki@job.com
johnk johnk@gmail.com
Then I tell git-quisk-stats that any of `[user: John Kravecki, email: john.kravecki@job.com, user:johnk, email:johnk@gmail.com]` is the same author.

**Describe alternatives you've considered**
Another solution would be to have an option to merge results into one. 
Example:
I have the same user with multiple username and/or email but I know that every time there is the same pattern, e.g. a surname kravecki. Then I can use `_GIT_LOG_OPTIONS="--author=kravecki` but I need another option, e.g. `--same-author` or `--merge-author` to get stats like it was a single user.

**Additional context**
None

**Comment by MuhammadSulaiman001** [comment]
This could be solved using [git .mailmap](https://git-scm.com/docs/gitmailmap), here is an example:

1. Create `.mailmap` file at the root of the project,
2. Here is an example content to write in `.mailmap` file:

```
Muhammad Sulaiman <muhammad.b.sulaiman001@gmail.com>
Muhammad Sulaiman <muhammad.b.sulaiman001@gmail.com> <m.sulaiman001@gmail.com>
Friend Name <hi@there.com>
Friend Name <hi@there.com> <90533@LAPTOP-ABV>
```

*Explanation*: the first line tells git that this name has this e-mail, second line tells git that there is another alias for this (name-email pair).. and so on.

This way, git will use `Muhammad Sulaiman <muhammad.b.sulaiman001@gmail.com>` whenever it sees `m.sulaiman001@gmail.com`..

Now run git-quick-stats again, issue solved.

I've documented the steps in the [following gist](https://gist.github.com/MuhammadSulaiman001/0005f9e01e46880f59150eaef29a3358) long time ago, refer to it for detailed description.

**Comment by tomice** [comment]
This is correct. You can use a `.mailmap` to solve this. It works as follows:

```bash
<Canonical name> <Canonical email>
<Alternative name or email> <Canonical email>
```

You're mapping a username or an email to another canonical email.

So in this case, you can do:
```bash
John Kravecki <john.kravecki@job.com>
johnk <john.kravecki@job.com>
john.kravecki@gmail.com <john.kravecki@job.com>
```

That should map all of your usernames and emails. Here's the git documentation on it: https://git-scm.com/docs/gitmailmap

Closing this for now since I'm doing some backlog cleanup, but if you find a bug with the mailmap feature, feel free to open another.
