### ISSUE TITLE
List changelogs is broken in version 2.5.4 on macos

### ISSUE THREAD

**Issue by himito** [arzzen/git-quick-stats#163]
Hi,

when I run 

`git-quick-stats -L`

I receive
```
    date: illegal option -- d
    usage: date [-jnRu] [-I[date|hours|minutes|seconds]] [-f input_fmt]
    [-r filename|seconds] [-v[+|-]val[y|m|w|d|H|M|S]]
    [[[[mm]dd]HH]MM[[cc]yy][.SS] | new_date] [+output_fmt]
```

It's related to  #152, and I think that is the following line:

https://github.com/arzzen/git-quick-stats/blob/7b1e0b2a65e9ecaa8a166d855028f223b563aa00/git-quick-stats#L419

**Comment by tomice** [comment]
Fixed with #164 . macOS now requires GNU Date installed via Homebrew
