### ISSUE TITLE
[Feature] Add First time commits since

### ISSUE THREAD

**Issue by TheLarkInn** [arzzen/git-quick-stats#17]
This is an awesome tool that I'll be using to generate a list of first time contributors to our [repos/org](http://github.com/webpack/webpack) to showcase on Twitter/medium. 

Id love to make the process even easier by having a command that would give me a list of users who contributed for the first time since a certain date. 

I'm not very well versed in bash (at all) so I figured I'd atleast request it as a feature. 

Nice work all this is wonderful. <3

**Comment by arzzen** [comment]
hi @TheLarkInn, from now, you can set variable `_GIT_SINCE`, `_GIT_UNTIL` and limit the `git log`

eg:
`export _GIT_SINCE="2017-20-01"`
`export _GIT_UNTIL="2017-22-01"`

then run `./git-quick-stats` (affect all stats, except "My daily status" and "Git changelogs" )

**Comment by TheLarkInn** [comment]
Thanks for the workaround, if you don't mind I'll share the repo in our spotlight as a "powered by" plug.

**Comment by arzzen** [comment]
Ok, thank you
