### ISSUE TITLE
A couple of new features

### ISSUE THREAD

**Issue by spirosmastorakis** [arzzen/git-quick-stats#21]
Hi, 

I forked your repo a couple days ago. I added a few new features (total number of commits, total number of code lines added/deleted, total number of contributors). These features also use the $_since $_until arguments, so that people can get the total number of commits/lines added/lines deleted/contributors within a certain period of time (for example, annually).

The reason I added those features is to see what is development trend and the community growth (in terms of contributors) for an open source project I have been working on.

The code is available here: https://github.com/spirosmastorakis/git-quick-stats

Let me know if you think these features might be useful.

**Comment by arzzen** [comment]
Hi @spirosmastorakis, nice work!

Thank you for your contribution.

However, I would recommend to join all summary stats into one and change group name "ndnSIM-related stats:" to more generic name.

**Comment by spirosmastorakis** [comment]
Yeah, sure.

I was planning to create a separate branch and submit a pull request, but I wanted to see first whether you are interested in merging features like those.

**Comment by arzzen** [comment]
@spirosmastorakis of course, you can send pull request ;)
