### ISSUE TITLE
Git changelogs only shows a single item

### ISSUE THREAD

**Issue by traveaston** [arzzen/git-quick-stats#23]
Not sure if this is the intended behaviour.

I was expecting something like a list of commit messages since the last tag or something, making it easier to write changelogs.

If single item is the intended behaviour, I'd like to offer this as a suggestion / enhancement.

**Comment by arzzen** [comment]
Hi, @traveaston thanks for your suggestion, 

you can update last version and then you can use updated output "Git changelogs" 

ps:
use `export _GIT_LIMIT=20` if you can change limit output
