### ISSUE TITLE
'Git commits by weekday' unsorted?

### ISSUE THREAD

**Issue by FLHerne** [arzzen/git-quick-stats#24]
Below is the output of "git commits by weekday" run on kdev-python.

I would have expected this to either be listed in week order or be sorted by the number of commits; instead the order appears random.

Is this expected?
```
        day     sum
        Tue     275     |=========
        Sat     349     |===========
        Thu     346     |===========
        Sun     410     |==============
        Mon     288     |=========
        Fri     361     |============
        Wed     308     |==========
```

**Comment by arzzen** [comment]
fixed, thanks @FLHerne
