### ISSUE TITLE
Supporting _GIT_EXCLUDE for detailedGitStats

### ISSUE THREAD

**Issue by mousepotatoz** [arzzen/git-quick-stats#25]
In my project, certain directories contain generated code and I would like to exclude them from the stats. This can be done by using the exclude pathspec documented here: https://github.com/git/git/commit/ef79b1f8704668a6cdf4278f9255e03ca785bfb4
For example, the following command will exclude gen1/gen2/gen3 from the log.
```
git log -- . ':!gen1' ':!gen2' ':!gen3' 
```

Can you add something like _GIT_EXCLUDE to support this use case?

**Comment by arzzen** [comment]
Hi, @mousepotatoz thanks for your suggestion,

you can update last version and then you can use updated output...

eg (in bash):
 `export _GIT_EXCLUDE="':\!gen1' ':\!gen2' ':\!gen3'"`

**Comment by mousepotatoz** [comment]
@arzzen Thanks for the quick turnaround. Tested your change with the following command:
```
_GIT_EXCLUDE='. :!idl' git quick-stats detailedGitStats
```

When do you plan to release it (so we could install it with brew)?

**Comment by mousepotatoz** [comment]
Actually I think it makes more sense to rename _GIT_EXCLUDE as _GIT_PATHSPEC, since it can do much more than just filtering: https://git-scm.com/docs/gitglossary#gitglossary-aiddefpathspecapathspec

**Comment by arzzen** [comment]
ok, @mousepotatoz updated

**Comment by mousepotatoz** [comment]
Thanks.  Please let me know when you plan to make the next release.
