### ISSUE TITLE
[FEATURE WISH] Recursive

### ISSUE THREAD

**Issue by SvenJuergens** [arzzen/git-quick-stats#28]
Hi,

this is a feature wish :) it would be awesome if this could be used in a dir with lot git projects and the stats would show a summary about all git projects.

Best Regards
Sven

**Comment by coagmano** [comment]
This would also be super useful for repos with submodules

**Comment by arzzen** [comment]
Hi @SvenJuergens, after a long time  ⏳

I don't have a project with submodules, so I can't test it, but a new feature was implemented a couple of days ago,
if you want to include submodule logs, you can try using the following: `export _GIT_LOG_OPTIONS="-p --submodule=log"`

ps: more info about [git log --submodule](https://git-scm.com/docs/git-log#Documentation/git-log.txt---submoduleltformatgt)
