### ISSUE TITLE
Map authors from .mailmap

### ISSUE THREAD

**Issue by mrflow** [arzzen/git-quick-stats#33]
Sometimes git repositories are slightly messed up with respect to author names. Git actually already sort-of has a fix for this issue (but as it seems only for git shortlog):

https://git-scm.com/docs/git-shortlog#_mapping_authors

It would be really nice if git-quick-stats would also use this file for "properly" mapping commits to authors.

**Comment by arzzen** [comment]
@mrflow thank you for reporting.
From now git-quick-stats respect .mailmap.
