### ISSUE TITLE
Cygwin git-quick-stats errors in script

### ISSUE THREAD

**Issue by zhevs** [arzzen/git-quick-stats#39]
Hello. I get some errors after run git-quick-stats in cygwin:
```
$ git-quick-stats
/usr/local/bin/git-quick-stats: line 2: $'\r': command not found
: invalid option nameick-stats: line 3: set: nounset
: invalid option nameick-stats: line 4: set: errexit
/usr/local/bin/git-quick-stats: line 5: $'\r': command not found
/usr/local/bin/git-quick-stats: line 28: syntax error near unexpected token `$'{\r''
'usr/local/bin/git-quick-stats: line 28: `function show_menu() {

```

**Comment by arzzen** [comment]
Hi @zhevs you can use in cygwin `/bin/dos2unix.exe /usr/local/bin/git-quick-stats` 
This will convert it to Unix format and you then should be able to run it.

**Comment by zhevs** [comment]
Thank you. It worked.

**Comment by hydra** [comment]
this worked for me too, but can we have the scripts with the right line endings committed to the repository so this doesn't cause any issues for anyone else in the future, perhaps using a .gitattributes file would help achieve this?
