### ISSUE TITLE
[Feature Request] Skip some dirs from the stats

### ISSUE THREAD

**Issue by rkyoku** [arzzen/git-quick-stats#40]
Hi,

Great tool! Thank you a lot, pretty useful to me right now.

However, I am concerned that the frontend guy gets in his stats all the lines of all the JS/CSS libs he added to the project. I am afraid that it could weigh a lot in the stats...

Is there a way to skip some folders, and/or some files by name?

Would be even more awesome, because even more precise!

What do you think?

Cheers,

**Comment by arzzen** [comment]
Hi @rkyoku you can use `_GIT_PATHSPEC` variable before run git-quick-stats 

example:
`export _GIT_PATHSPEC=':!assets/*.js' && ./git-quick-stats`

more info about pathspec: https://git-scm.com/docs/gitglossary#gitglossary-aiddefpathspecapathspec
