### ISSUE TITLE
[Bug] Last commit time is determined incorrectly

### ISSUE THREAD

**Issue by dak** [arzzen/git-quick-stats#41]
#### Expected behavior and actual behavior.
Expected: Show date and time of the most recent commit in the commit history for an author.
Actual: Shows the date and time of the last commit attributable to the author in the commit history.

* a1234567 - (2018-05-01) (HEAD -> master) Commit #1 \<Author>
* b2345678 - (2018-06-01) Commit #2 \<Author>

The above commit log will show Author's last commit was 2018-05-01, instead of 2018-06-01.

**Comment by ksze** [comment]
I'm confused. What's the difference between:
- "the most recent commit in the commit history for an author"

vs

- "the last commit attributable to the author in the commit history"

**Comment by tomice** [comment]
Adding to this, as I believe this is the bug that's being referenced. If it is not, please correct me.

Expected: When selecting "Git changelogs (last 10 days)" or "Git changelogs by author" and providing an author to search on, it should show the latest commit in the repo at the top

Actual: When selecting "Git changelogs (last 10 days)" or "Git changelogs by author" and providing an author to search on, the latest **local** commit gets moved to the incorrect date string

Steps to reproduce:
1) Inside the repo, launch git quick-stats
2) Select "Git changelogs (last 10 days)"
3) Note the output in the terminal
![image](https://user-images.githubusercontent.com/8818630/75630272-37b56900-5bb7-11ea-965d-b322abd528ba.png)
4) Add a file and commit it to the repo (touch foo ; git add foo ; git commit -m "foo"). However, do not push it to the remote repo yet.
5) Launch git quick-stats again
6) Select "Git changelogs (last 10 days)"
7) Note the blank entry at the top, along with the latest commit moved to an incorrect date
![image](https://user-images.githubusercontent.com/8818630/75630279-456aee80-5bb7-11ea-9ab4-8e96e5d40fc4.png)

Also, note that the top date always appears to be empty. This is a separate, albeit most likely related, bug.
