### ISSUE TITLE
fatal: While expanding alias 'quick-stats': ' /usr/local/bin/git-quick-stats': No such file or directory

### ISSUE THREAD

**Issue by jision** [arzzen/git-quick-stats#6]
Just cant seem to figure it out !!! help needed 

Followed the read.md but git quick-stats not working

**Comment by arzzen** [comment]
hi, you can try this?

`git config --global alias.quick-stats '! /your/path/where/is/git-quick-stats'`

`/your/path/where/is/` change for your path
