### ISSUE TITLE
List of all the branches

### ISSUE THREAD

**Issue by mohlek** [arzzen/git-quick-stats#7]
When generating a list of all branches the program crashes.

```
List of all the branches, ordered by most recent commits:
fatal: unknown field name: color:blue
```

**Comment by mohlek** [comment]
color:blue is available since git-1.9
http://stackoverflow.com/questions/18070271/git-for-each-ref-with-a-coloured-format-string

There are some distro which may ship older versions. CentOS comes with 1.8.3.1.
Maybe you should check for the required version

**Comment by mohlek** [comment]
%(color:XXX) in general isn't available. Not only %(color:blue) :)
I upgraded my git so it doesn't affect me now but maybe some other guys?!

**Comment by arzzen** [comment]
thanks, i removed them
