### ISSUE TITLE
Support Co-authored Commits

### ISSUE THREAD

**Issue by YoussefRaafatNasry** [arzzen/git-quick-stats#70]
- Running `9) Git commits per author` gives the following output:

```git
Git commits per author:

204  Youssef Raafat    49.5%
189  Michael Safwat    45.9% 
 19  Micheline Medhat  4.6%
```

While the GitHub [repo](https://github.com/MichaelSafwatHanna/FitnessApp) contains the following [stats](https://github.com/MichaelSafwatHanna/FitnessApp/graphs/contributors) due to [Co-authors](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors).

![image](https://user-images.githubusercontent.com/41103290/58202457-d7180800-7cd7-11e9-86cf-72c3454481dc.png)

- If I ran `git shortlog --grep='Co-authored-by: Youssef Raafat' -s -n ` the output will be `77  Michael Safwat`.
- Adding the **77 commit** from `shortlog` to the **204 commits** of the previous output gives us something near GitHub [stats](https://github.com/MichaelSafwatHanna/FitnessApp/graphs/contributors).

So is it possible to add option to **count commits by authors & co-authors**?

**Comment by ProcrastinatorCp** [comment]
It seems the current github stats doesn't include the co-authored commits and is same as what's printed by `git-quick-stats` ** (10. Git commits per author) **

Repo : https://github.com/MichaelSafwatHanna/FitnessApp
- As output by git-quick-stats : 
```
   205	Youssef Raafat    49.6%
   189	Michael Safwat    45.8%
    19	Micheline Medhat  4.6%
```
- As shown by repo's contributor tab : 
![Screen Shot 2019-10-06 at 2 54 50 PM](https://user-images.githubusercontent.com/29228904/66265454-49355780-e849-11e9-9954-a6304753452d.png)
 
@YoussefRaafatNasry 
I am not sure if it's the ideal behaviour or a bug in **github** itself.

**Comment by tomice** [comment]
I am seeing the same thing @ProcrastinatorCp is seeing with regards to how GitHub is parsing the stats given the current information. That said, I think this feature in general is a good idea. It might be worth looking into supporting the Linux kernel commit message conventions by also supporting the following:

> Acked-by
Co-Authored-By
Reported-by
Reviewed-by
Signed-off-by
Suggested-by
Tested-by

https://git.wiki.kernel.org/index.php/CommitMessageConventions

**Comment by YoussefRaafatNasry** [comment]
GitHub themselves deprecated this feature.

![image](https://user-images.githubusercontent.com/41103290/66271515-16965980-e85f-11e9-9ca2-048009f4d2d8.png)

But I think it's the concern of this tool to analyze and get as much statistics as possible about git repositories. So, it would be a nice feature to know how many commits someone co-authored.

**Comment by ProcrastinatorCp** [comment]
Agree. Good to have this feature. 
I will give it a go sometime in the next week.
