### ISSUE TITLE
[Feature] Promo site for custom domain git-quick-stats.sh

### ISSUE THREAD

**Issue by arzzen** [arzzen/git-quick-stats#76]

**Comment by ProcrastinatorCp** [comment]
Hi @arzzen, 
Do you have a rough plan about the site ? 
Mostly in terms of : 
- Design (like any sample/similar site)
- Tech stack
- Others

IMHO if the tasks are defined in modular level, it would be easier for contributors to work on it.

**Comment by arzzen** [comment]
Hi @ProcrastinatorCp, thanks for your interest.
We need a proper website, with docs, examples, etc.

**Design:**
Use some opensource one-page theme. 
Some examples (element layouts): https://storybook.js.org/, https://hyper.is/  etc.

**Tech stack:**
Basic static generation (e.g. with Gatsby, Jekyll...) from markdown would probably work just fine.
All work must be pushed to the gh-pages branch or to docs folder, where the current one lives.

**Other plans:**
- create som promo stickers
- migrate this repository to github organisation

**Comment by arzzen** [comment]
Promo site was created at https://git-quick-stats.sh/.
