### ISSUE TITLE
please install to /usr/lib/git-core not /usr/bin

### ISSUE THREAD

**Issue by kilobyte** [arzzen/git-quick-stats#77]
All other `git` programs: built-in, official extension, all third-party extensions I've looked at, are invoked via `git foo-bar` rather than `git-foo-bar`.  Except for your tool.

Thus, it would be nice if you installed to `/usr/lib/git-core` instead of `/usr/bin`.  If you're concerned about your old users' muscle memory, a symlink from one location to the other might be good.

**Comment by tomice** [comment]
Installation destination preference aside, this tool can be invoked either via `git-quick-stats` or `git quick-stats`. Both should be valid. I noticed that this feature may have been lost in the documentation and the documentation should probably be updated to reflect this.
