### ISSUE TITLE
[Feature] Introduce translation support

### ISSUE THREAD

**Issue by arzzen** [arzzen/git-quick-stats#78]
Add support for another languages.
Translations for German, Spanish, Esperanto etc

(original issue #75)

**Comment by tomice** [comment]
**Info dump/thoughts:**
The best way I can think of doing this would be to setup a variable for every string, and have separate files in a "lang" folder that get sourced by git-quick-stats. Here is what the directory structure would look like:

```
ice@PC-PC:~/git-quick-stats(master)$ tree
.
├── Dockerfile
├── foo
├── git-quick-stats
├── git-quick-stats.1
├── lang
│   ├── deu
│   ├── eng
│   ├── epo
│   ├── fin
│   ├── fra
│   ├── jpn
│   └── nld
├── LICENSE
├── Makefile
├── README.md
└── tests
    ├── assert.sh
    └── commands_test.sh
```

All strings would now be variables sourced from these files that utilize a common variable name. For example, on line 53 in the checkUtils function, "local -r msg" would be changed to "CHECK_UTILS_MSG" and moved to every one of these files. So deu would have "CHECK_UTILS_MSG", eng would have "CHECK_UTILS_MSG", epo would have "CHECK_UTILS_MSG", and so on. CHECK_UTILS_MSG would then equal the appropriate text for that particular language. In eng, it would be:
```
CHECK_UTILS_MSG="not found. Please make sure this is installed and in PATH."
```

That means line 53 would be removed and line 59 would be changed to:
```
command -v "$u" >/dev/null 2>&1 || { echo >&2 "$u ${CHECK_UTILS_MSG}"; exit 1; }
```

The language could be set via command line similar to how we do _GIT_SINCE and so on. Or we could attempt to parse $LANG to determine the appropriate language. These language files would essentially get sourced at startup.

**Opinion:**
I usually don't like inserting my personal opinions in these, but I feel this would be extremely difficult to do in bash reliably that would work across various installations of Linux, UNIX, and macOS. A lot of this would be shell encoding specific, as well as locale specific. 

Some may wish to have their shell language be a different language from their OS language for various reasons, and that could cause some issues if we try to guess the language via $LANG. A good chunk of the script would need to be rewritten.

I feel this would be better suited for something like Python to handle this, as we could then utilize classes, more robust design patterns, a nice database for all of the languages, and be able to better abstract the random quirks that occur across shell platforms by utilizing Python's built-in libraries instead for most of what we are doing.

I have read this before: https://www.linuxjournal.com/content/internationalizing-those-bash-scripts

And I have tried a quick test with it, but I found it didn't work out too well across different platforms upon my first go.

If anyone has a better idea of how to do this without resorting to a different language such as Python, Ruby, or what have you, I would love to hear it, as this is something I am quite interested in doing reliably.

**Comment by arzzen** [comment]
@tomice thank you for your elaboration 👍 ,

I'm adding more options on how to use translate in bash;
You can use the [$"…" syntax](https://www.gnu.org/software/bash/manual/bash.html#Locale-Translation) to specify a string that is to be translated according to the locale. The translations must be in a [message catalog file](https://www.gnu.org/software/libc/manual/html_node/The-message-catalog-files.html); see the bash manual for where this file is located and the Glibc manual for the format of the file.  See practical example [here](https://iranzo.github.io/blog/2017/10/26/i18n-and-bash8-in-bash/#bash-i18n).

But, my personal opinion is that the English translation is quite sufficient, it is generally used. 

So, for now, I close this issue.
