### ISSUE TITLE
mac 10.15 output: unknown terminal "xterm"

### ISSUE THREAD

**Issue by windard** [arzzen/git-quick-stats#84]
#### Expected behavior and actual behavior.
show git stats

### Steps to reproduce the problem.
    
    just run git-quick-stats
#### Specifications like the version of the project, operating system, or hardware.

output: unknown terminal "xterm"

**Comment by tomice** [comment]
While I cannot upgrade to 10.15 yet due to some software incompatibility issues I have, I believe this is most likely an error due to how the `$TERM` variable is set. If you do an `echo $TERM`, what does it say?

**Comment by arzzen** [comment]
@windard please, what is your output of command `echo $TERM` (is still relevant this issue?)

**Comment by kankowski** [comment]
On macOS 10.15, I experience the following error:
```
$ git-quick-stats
/usr/local/bin/git-quick-stats: line 26: ${_merges,,}: bad substitution
```
How could I get around it? Thanks.

**Comment by tomice** [comment]
Sorry, that's a Bash 4.0-ism. OS X runs an old version of Bash, and I forgot lowercase variable expansion didn't occur until 4.0. It's not necessary, as it was meant to be a quick string sanitization effort.

To fix it, remove the two commas from that variable on lines 26 and 28.

I'll make a fix when I get some time later.

**Comment by tomice** [comment]
Given the lack of feedback from the OP on the issue with the `$TERM` variable, I vote we close this as I have been unable to replicate this issue. I have tried the following on macOS 10.14:

`TERM=xterm-256color` runs successfully
`TERM=xterm` runs successfully
`TERM=""` reports TERM environment variable not set
`TERM="unknown"` reports 'unknown': I need something more specific
`TERM="foo"` reports terminals database is inaccessible

The following link seems to indicate it is a macOS issue regarding corruption or an incorrectly set `$TERM` variable: https://apple.stackexchange.com/questions/26662/unknown-terminal-xterm-256color
