### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by golflima** [arzzen/git-quick-stats#85]
Hi,
I made a small docker image for your tool, but if you'd like to integrate the dockerfile directly in your project let me know: I'll made a pull request and redirect my repo to yours.
The repo: https://github.com/frxyt/docker-git-quick-stats
It's easier to integrate your tool in a CI/CD toolchain with docker that's why I made it in the first place.

**Comment by arzzen** [comment]
Hi @golflima , thanks for your improve, 
It will be nice if you create pull request

**Comment by golflima** [comment]
Hi @arzzen , I'll make it shortly.
